# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
exclude: ['README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "WSTAR-SNU, 2018 Winter"
email: "wstar-snu@gmail.com"
description: "This is descriptions"
baseurl: "/website-workshop-2018winter"
url: "https://jaeyeong-yang.com"
permalink: "/notice/:title"
useFavicons: false
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Head
#metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/schedule/", text: "Schedule"}
  - {permalink: "/speakers/", text: "Speakers"}
  # - {permalink: "/notice/", text: "Notice"}
  - {permalink: "/apply/", text: "Application"}
bottomNavigationLinks:
  # - {link: "", text: "Apply"}
rightNavigationButtons:
  # - {link: "", text: "Apply"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: |
  <strong>WSTAR @ SNU</strong> <br>
  <div style="font-size: .7em; margin: 1.5rem 0; line-height: 1.3em;">
    Workshop for <br class="visible-xs"> Statistical Tools & <br>
    Analytical Researches <br>
    at Seoul National University
  </div>
eventDate: "2019년 2월 18일 ~ 22일"
heroButtons:
  # - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
  # - {permalink: "/apply", text: "Apply"}

# About Block
aboutTitle: "Vision"
aboutDescription: |
  뇌-인지과학 분야에서 신경세포 혹은 네트워크의 정보처리 기전을 연구하기 위해
  실험 데이터를 수집하는 방법은 점차 고도화되고 있으며 데이터의 성격도 복잡해지고 있다.
  특히, 신경세포의 활동전위를 측정하여 발화패턴과 뇌의 정보처리 간의 관계를 연구하는
  전기생리학 분야와 기능적 자기 공명 영상(functional magnetic resonance imaging; fMRI) 등의
  신경영상(neuroimaging)을 통해 뇌의 활성패턴을 연구하는 분야에서 다루는 자료를
  효과적으로 분석하기 위해서는 자료의 수집 과정에 대한 이해와 적절한 통계적 분석법에
  대한 이해가 동시에 필수적으로 이루어져야 한다. 또한, 방대한 데이터가 같는 의미를
  체계적으로 이해하고 유용한 정보를 데이터로부터 도출하기 위해서는 계산적 모델링을 통해
  정량적 이론을 구축할 필요가 있다. 본 겨울학교에서는 학생들이 복잡한 신경과학 데이터의
  속성을 이해하고 이에 맞는 통계적 분석법을 적용하여 실제 연구현장에서 활용할 수 있도록
  서울대학교의 신경과학자들과 통계학자들이 중심이 되어 강의와 실습을 병행할 계획이다.
aboutBlock:
  # - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
  # - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
  # - {count: "50", specialCharacter: "+", info: "openings", detail: ""}
  # - {count: "5", specialCharacter: "", info: "days", detail: ""}
  # - {count: "5", specialCharacter: "", info: "speakers", detail: "from Seoul National University"}

# Latest News Block
latestNewsTitle: "최근 공지글"

# Rockstar Speakers Block
# rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "더 보기"

# Location Block
# locationBlockTitle: "Location"
# eventLocationName: "Conference Hall"
# eventLocationLink: "https://www.google.com/maps/place/%EC%84%9C%EC%9A%B8%EB%8C%80%ED%95%99%EA%B5%90/@37.4598862,126.9497166,17z/data=!3m1!4b1!4m5!3m4!1s0x357c9fe8a0a1e2a5:0xa1e2eebc04f0c5e7!8m2!3d37.459882!4d126.9519053"
# eventStreetAddress: "Gwanak-ro 1 Seoul National University"
# eventAddressLocality: "관악구"
# eventAddressLocalityRegion: "Lvivska"
# eventPostalCode: "08826"
# eventAddressCountry: "South Korea"
# eventStartTime: "2019-02-18T09:00"
# eventDoorTime: "09:00"
# eventEndTime: "2019-02-22T18:00"
# eventPlaceCoordinates: "37.4598862, 126.9497166"
# mapCenterCoordinates: "37.4598862, 126.9497166"
# mapMobileCenterCoordinates: "37.4598862, 126.9497166"

# Venue Block
# venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
# tweetsFeedImage: ""
# tweetsFeedTitle: ""
# twitterHashTag: ""
# twitterFeed: ""

# Partners Block
# organizersTitle: "Organizers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
# ticketsTitle: "Pricetable"
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
# ticketsOffers:
#  -
#   name: "Early Bird"
#   price: "350"
#   priceCurrency: "UAH"
#   ticketsNumber: "150"
#   ribbon: "-5%"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"
#  -
#   name: "Last Chance"
#   price: "450"
#   priceCurrency: "UAH"
#   ticketsNumber: "100"
#   ribbon: "-20%"
#   featured: true
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-23T23:59"
#   disabled: true
#  -
#   name: "Student"
#   price: "200"
#   priceCurrency: "UAH"
#   ticketsNumber: "50"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-20T10:00"
#   validThrough: "2014-10-23T23:59"
#   soldOut: true
#   soldOutText: "Sold Out"

# Application
# applicationTitle: 지원요망
applicationBlocks:
  - 
    title: 마감일시
    image: calendar.svg
    text: 2018년 12월 15일<br> 오후 5시까지
  -
    title: 모집대상
    image: students.svg
    text: 현재 서울대학교에 재학 중인 대학원생<br> 혹은 2019년 3월에 입학 예정인 예비 대학원생
  -
    title: 자격요건
    image: programming.svg
    text: |
      R이나 MATLAB을 이용하여 <br>
      프로그래밍이 가능한 학생들을 우선 선발 <br>
      (기초가 부족한 경우 아래 추천 강의를 활용하여 <br>
      기초 프로그래밍을 숙지해야 참가 가능)
applicationUrl: \#
applicationButtonText: 신청하기

# Refcourses
refcoursesTitle: 추천 프로그래밍 강의

# Footer
socialLinks:
  # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
  # - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
  # - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
  # - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
  # -
  #   title: "Links"
  #   links:
  #     - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
  #     - {link: "https://developers.google.com", text: "Google Developers"}
  -
    title: "Contacts"
    links:
      - {link: "mailto:wstar-snu@gmail.com", text: "wstar-snu@gmail.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: ""

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
