# Plugins
plugins:
- jekyll-sitemap
- jekyll-compass
safe: false

# Build Settings
markdown: kramdown
exclude: ['README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DANS-SNU, 2018 Winter"
author: "DANS-SNU"
email: "snudans@gmail.com"
description: ""
baseurl: ""
url: ""
permalink: "/notice/:title"
useFavicons: false
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Head
#metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
#  - {permalink: "/schedule/", text: "Schedule"}
#  - {permalink: "/speakers/", text: "Speakers"}
#  - {permalink: "/notice/", text: "Notice"}
#  - {permalink: "/apply/", text: "Application"}
bottomNavigationLinks:
#  - {link: "https://goo.gl/forms/dCJ8PsCbMrfb0Dt72", text: "Apply"}
rightNavigationButtons:
#  - {link: "https://goo.gl/forms/dCJ8PsCbMrfb0Dt72", text: "Apply"}

# Hero Block
heroImage: "hero-new.jpg"
heroTitle: |
  <div class="logo-dans">
    <strong>DANS</strong>
    <small>
      Data Analysis in Neuroscience<br>
      at Seoul National University
    </small>
  </div>
  <div class="hero-title">
    SNU 신경통계 <br class="visible-xs"> 겨울학교 워크샵
  </div>
eventDate: |
  2019년 2월 18일 ~ 22일
  <span class="hidden-xs" style="margin: 0 0.5rem;">|</span>
  <br class="visible-xs">
  서울대학교 203동 106호
heroButtons:
  - {permalink: "#application-title", text: "신청하기"}
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# About Block
aboutTitle: "Vision"
aboutDescription: |
  뇌-인지과학 분야에서 신경세포 혹은 네트워크의 정보처리 기전을 연구하기 위해
  실험 데이터를 수집하는 방법은 점차 고도화되고 있으며 데이터의 성격도 복잡해지고 있다.
  특히, 신경세포의 활동전위를 측정하여 발화패턴과 뇌의 정보처리 간의 관계를 연구하는
  전기생리학 분야와 기능적 자기 공명 영상(functional magnetic resonance imaging; fMRI) 등의
  신경영상(neuroimaging)을 통해 뇌의 활성패턴을 연구하는 분야에서 다루는 자료를
  효과적으로 분석하기 위해서는 자료의 수집 과정에 대한 이해와 적절한 통계적 분석법에
  대한 이해가 동시에 필수적으로 이루어져야 한다. 또한, 방대한 데이터가 갖는 의미를
  체계적으로 이해하고 유용한 정보를 데이터로부터 도출하기 위해서는 계산적 모델링을 통해
  정량적 이론을 구축할 필요가 있다. 본 겨울학교에서는 학생들이 복잡한 신경과학 데이터의
  속성을 이해하고 이에 맞는 통계적 분석법을 적용하여 실제 연구현장에서 활용할 수 있도록
  서울대학교의 신경과학자들과 통계학자들이 중심이 되어 강의와 실습을 병행할 계획이다.
aboutBlock:
  # - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
  # - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
  # - {count: "50", specialCharacter: "+", info: "openings", detail: ""}
  # - {count: "5", specialCharacter: "", info: "days", detail: ""}
  # - {count: "5", specialCharacter: "", info: "speakers", detail: "from Seoul National University"}

# Latest News Block
latestNewsTitle: "최근 공지글"

# Rockstar Speakers Block
# rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "더 보기"

# Schedule-Summary
scheduleSummaryTitle: Schedule
scheduleSummaryButton: false
scheduleSummaryButtonText: 더 보기
scheduleSummaryImage: schedule.png
scheduleSummaryImageAlt: Schedule
scheduleSummaryText: |
  2019년 2월 18일 ~ 22일 (총 5일),
  <br class="visible-xs">
  서울대학교 203동 106호

# Application
applicationTitle: Application
applicationBlocks:
  -
    title: 모집대상
    image: students.svg
    text: 현재 서울대학교에 재학 중인 대학원생<br> 혹은 2019년 3월에 입학 예정인 예비 대학원생
  -
    title: 자격요건
    image: programming.svg
    text: |
      R이나 MATLAB을 이용하여 <br>
      프로그래밍이 가능한 학생들을 우선 선발 <br>
      (기초가 부족한 경우 아래 추천 강의를 활용하여 <br>
      기초 프로그래밍을 숙지하여야 참가 가능)
  - 
    title: 마감일시
    image: calendar.svg
    text: 2018년 12월 15일<br> 오후 5시까지
applicationUrl: https://goo.gl/forms/dCJ8PsCbMrfb0Dt72
applicationButtonText: 신청하기

# Poster
posterTitle: Poster
posterThumbnail: "thumbnail.jpg"
posterUrl: "/assets/poster.pdf"

# Refcourses
refcoursesTitle: 추천 프로그래밍 강의

# Footer
socialLinks:
#  - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
#  - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
#  - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
#  - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
  -
    title: "Contacts"
    links:
      - {link: "mailto:snudans@gmail.com", text: "snudans@gmail.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: ""

# Speakers List Block
showSessions: false
